version: '3.1'

services:

  backend:
    image:  node:14-alpine
    command: sh -c "yarn && yarn start"
    ports:
      - 8080:8080
      - 9229:9229
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  frontend:
    image:  node:14-alpine
    command: sh -c "yarn && yarn start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend:/app
  
  db:
    image: mysql
    volumes:
      - db-todos:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 3306:3306

volumes:
  db-todos: